### ISSUE TITLE
屏幕模糊增强建议

### ISSUE THREAD

**Issue by SapientSi** [UMU618/PowerEconomizer#4]
有时候我在看视频 但是晚上看着看着就睡着了 有时候可能会上一个厕所 然后回来继续看 
那么仅仅只是屏幕模糊不足以最大程度节省电源 可以让屏幕模糊的同时暂停系统所有视频音频的播放 取消屏幕模糊时重新开始播放视频

**Comment by UMU618** [comment]
屏幕模糊和节省电源是两个功能，它们没联系，只是我恰恰把它们放在同一个程序里，这样我就不需要再开一个屏幕模糊的程序（[https://github.com/UMU618/win10-screen-blur](https://github.com/UMU618/win10-screen-blur)）了……
